version: '3'
services: 
  rabbit-ram:
    container_name: rabbit-ram
    hostname: rabbit-ram
    image: bijukunjummen/rabbitmq-server:3.6.5
    ports:
      - "4369:4369"
      - "5671:5671" 
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    environment: 
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq
      - RAM_NODE=true
#    volumes:
#      - "$PWD/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"