version: '3'
services: 
  rabbitmq:
    container_name: rabbit-master
    command: "rabbitmq-server"
    image: rabbitmq:3-management
    hostname: rabbit-master
    ports:
      - "4369:4369"
      - "5671:5671" 
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "$PWD/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"